service: github-hook

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get